#include "coaster/coaster.hpp"
#include <fstream>
#include <filesystem>
#include <iostream>
#include <sstream>
#include <stdexcept>
using namespace coaster;
static int checks=0;
static void check(bool b,const char* why){++checks;if(!b)throw std::runtime_error(why);}
static void near(double a,double b,double eps,const char* why){check(std::isfinite(a)&&std::abs(a-b)<=eps,why);}
static bool code(const ValidationReport& r,const char* c){for(const auto& e:r.errors)if(e.code==c)return true;return false;}
static Targets synthetic(){Targets t;t.referenceExposure=11;t.referenceId="rf-v1:"+std::string(64,'a');auto& b=t.reference;b.processed=true;b.method="piecewise-linear-positive10s-v1";b.groupId=t.referenceId;b.ride="SYNTHETIC fixture, not I305";b.configuration="synthetic-cfg";b.seat="front";b.device="synthetic-device";b.calibrationId="synthetic-cal";b.minimum=10;b.median=11;b.maximum=12;
    for(int i=0;i<3;++i){ReferenceRecording r;r.recordingId="synthetic-"+std::to_string(i);r.rawSha256=std::string(64,char('a'+i));r.canonicalSha256=std::string(64,char('a'+i));r.analysisSha256=std::string(64,char('a'+i));r.source="SYNTHETIC fixture";r.notes="No measured data";r.sampleRateHz=r.sampleRateMinHz=r.sampleRateMaxHz=100;r.exposure=10+i;b.recordings.push_back(r);}return t;}
static uint64_t hash(const std::string& s){uint64_t h=14695981039346656037ull;for(unsigned char c:s){h^=c;h*=1099511628211ull;}return h;}
static void write(const std::filesystem::path& p,const std::string& payload){std::ofstream f(p,std::ios::binary);f<<"COASTER 5 "<<payload.size()<<' '<<hash(payload)<<'\n'<<payload;}
static std::string bytes(const std::filesystem::path& p){std::ifstream f(p,std::ios::binary);return {std::istreambuf_iterator<char>(f),{}};}
int main(){try{
    Targets unavailable;check(referenceStatus(unavailable)=="unavailable","Missing stays unavailable");Targets manual;manual.referenceExposure=11;manual.referenceId="SYNTHETIC manual";check(referenceStatus(manual)=="user-configured-unverified","Manual stays unverified");
    auto t=synthetic();check(validateReference(t).valid(),"Synthetic typed fixture structurally valid");std::string error;Targets parsed=manual;check(parseReference(serializeReference(t.reference),parsed,error),"Typed round trip");check(serializeReference(parsed.reference)==serializeReference(t.reference),"All typed evidence preserved");
    for(int problem=0;problem<9;++problem){auto bad=t;if(problem==0)bad.reference.median=12;if(problem==1)bad.reference.recordings[1].canonicalSha256=bad.reference.recordings[0].canonicalSha256;if(problem==2)bad.reference.recordings[1].recordingId=bad.reference.recordings[0].recordingId;if(problem==3)bad.reference.method="unknown";if(problem==4)bad.reference.recordings[0].source="";if(problem==5)bad.reference.recordings[0].sampleRateHz=INFINITY;if(problem==6)bad.reference.recordings[0].analysisSha256="bad";if(problem==7)bad.reference.minimum=-1;if(problem==8)bad.reference.recordings.resize(2);check(!validateReference(bad).valid(),"Malformed reference fails structural/semantic validation");Targets retained=t;check(!parseReference(serializeReference(bad.reference),retained,error),"Malformed interchange rejected");check(serializeReference(retained.reference)==serializeReference(t.reference),"Rejected reference import retains last target");}
    auto invalidUtf=t;invalidUtf.reference.ride=std::string(1,char(0xff));check(!validateReference(invalidUtf).valid(),"Invalid UTF-8 rejected");
    auto missingQuartile=t;missingQuartile.reference.q1=1;check(!validateReference(missingQuartile).valid(),"Unavailable quartile placeholder enforced");
    auto four=t;four.reference.hasQuartiles=true;four.reference.recordings.push_back(four.reference.recordings.back());auto& fourth=four.reference.recordings.back();fourth.recordingId="fourth";fourth.canonicalSha256=std::string(64,'d');fourth.exposure=13;four.reference.median=four.referenceExposure=11.5;four.reference.maximum=13;four.reference.q1=10.25;four.reference.q3=12.75;check(validateReference(four).valid(),"Exclusive quartiles match processor n4");
    auto conflict=t;conflict.referenceExposure=99;check(!validateReference(conflict).valid(),"Duplicated scalar mismatch rejected");
    auto constant=summarizeAxis(std::vector<double>(201,3),.1);near(constant.meanG,3,1e-12,"Constant mean");near(constant.mean1sMin,3,1e-12,"1s min");near(constant.mean10sMax,3,1e-12,"10s max");near(constant.maxRateGps,0,0,"Constant rate");std::vector<double> ramp;for(int i=0;i<200;++i)ramp.push_back(-5+i*.1);auto rs=summarizeAxis(ramp,.1);near(rs.maxRateGps,1,1e-12,"Signed ramp rate");near(rs.mean1sMin,-4.55,1e-12,"Signed zero-order 1s window");check(std::isnan(summarizeAxis({1,2},.1).mean1sMax),"Insufficient windows absent");
    GenerationRequest req;req.seed=3;req.simulationStep=1./960;req.terrain.kind=TerrainKind::Flat;req.targets.requireIntensity=false;
    // Flat seed3 provides an actually assessed complete-circuit fixture. The
    // expanded canyon3 profile can fail the optional rate convergence gate.
    // Optional assessment must participate in candidate search. A proof ride
    // accepted with this axis unassessed need not converge after a later upgrade.
    req.limits.maxLateralRateGps=1000;auto d=generate(req);check(d.accepted(),"Requested lateral assessment participates in generation and converges");
    d.request.limits.maxLateralRateGps=std::numeric_limits<double>::quiet_NaN();
    for(int seat=0;seat<3;++seat){const auto& st=d.simulation.metrics.seats[seat];check(st.axes[2].maxRateGps>0,"Longitudinal rates measured per seat");check(st.longestAbove2Seconds<=st.positiveAbove2Seconds&&st.longestAirtimeSeconds<=st.airtimeBelowZeroSeconds,"Longest bout cannot exceed cumulative duration");}
    near(d.simulation.metrics.maxJerkGps,std::max({d.simulation.metrics.seats[0].axes[0].maxRateGps,d.simulation.metrics.seats[1].axes[0].maxRateGps,d.simulation.metrics.seats[2].axes[0].maxRateGps}),1e-12,"Global and per-seat analytic vertical rates agree");
    auto constrained=d;constrained.request.limits.maxLongitudinalRateGps=.00001;constrained.report={};evaluateTargets(constrained);check(code(constrained.report,"LONGITUDINAL_FORCE_RATE"),"Explicit provisional longitudinal gate rejects");check(!code(d.report,"LONGITUDINAL_FORCE_RATE"),"Unset axis gate unassessed, no fabricated threshold");
    req.limits.maxLateralRateGps=INFINITY;check(code(validateRequest(req),"AXIS_RATE_CONFIG"),"Infinite axis gate invalid");req.limits.maxLateralRateGps=0;check(code(validateRequest(req),"AXIS_RATE_CONFIG"),"Zero axis gate invalid");
    auto rateAssessed=d;rateAssessed.request.limits.maxLateralRateGps=1000;verifyConvergence(rateAssessed);check(rateAssessed.accepted(),"Improved canonical frame has an actually converged assessed lateral profile");
    auto underresolved=rateAssessed;underresolved.request.simulationStep=1./30;underresolved.simulation=simulate(underresolved.track,underresolved.operations,underresolved.request.train,underresolved.request.simulationStep);underresolved.report={};verifyConvergence(underresolved);
    check(!underresolved.accepted()&&underresolved.convergence.performed&&!underresolved.convergence.passed&&code(underresolved.report,"CONVERGENCE_METRIC"),"An underresolved actual simulation cannot commit acceptance");
    check(std::any_of(underresolved.convergence.metrics.begin(),underresolved.convergence.metrics.end(),[](const auto& metric){return metric.name.find(".lateral.maxRateGps")!=std::string::npos&&metric.absoluteDifference>=metric.tolerance;}),"Explicit lateral assessment remains checked when its measured rate is unresolved");
    d.request.targets=t;d.request.targets.requireIntensity=false; // Synthetic metadata only; uncalibrated horizontal rates remain unassessed.
    verifyConvergence(d);check(d.accepted(),"Typed metadata fixture retains actual half-step verification");
    const auto folder=std::filesystem::path(__FILE__).parent_path().parent_path().parent_path()/"test-artifacts";std::filesystem::create_directories(folder);auto good=folder/"typed.coaster",bad=folder/"bad.coaster";
    check(saveDesign(d,good.string(),error),"Typed design saves");Design loaded;check(loadDesign(good.string(),loaded,error),"Typed design loads");check(serializeReference(loaded.request.targets.reference)==serializeReference(t.reference),"Typed metadata persists exactly");check(std::isnan(loaded.request.limits.maxLateralRateGps)&&std::isnan(loaded.request.limits.maxLongitudinalRateGps),"Unset axes persist unassessed");check(reportJson(d)==reportJson(loaded),"Geometry replay and all report fields identical");
    const auto saved=bytes(good),payload=saved.substr(saved.find('\n')+1);const auto extension=payload.find("EXTENSIONS ");check(extension!=std::string::npos,"Extension tail present");
    for(const auto& tail:std::vector<std::string>{"EXTENSIONS 1\nUNKNOWN 1 1\nx","EXTENSIONS 1\nREFERENCE 1 1048577\nx","EXTENSIONS 2\nAXIS_RATE_LIMITS 1 8\n0 0 0 0\nAXIS_RATE_LIMITS 1 8\n0 0 0 0\n","EXTENSIONS 1\nAXIS_RATE_LIMITS 1 8\n1 0 0 0\n","EXTENSIONS 1\nREFERENCE 2 1\nx","EXTENSIONS 1\nREFERENCE 1 20\nx"}){write(bad,payload.substr(0,extension)+tail);auto prior=loaded;check(!loadDesign(bad.string(),prior,error),"Malformed/unknown extension fails closed");check(reportJson(prior)==reportJson(loaded),"Failed load retains prior design");}
    // A well-formed rate extension must reach actual half-step validation. The
    // improved canonical frame supports this profile without a trust upgrade.
    const std::string axisBlock="1 1000 0 0\n";
    const auto directoryEnd=payload.find('\n',extension);std::istringstream directory(payload.substr(extension,directoryEnd-extension));std::string directoryTag;size_t originalCount;directory>>directoryTag>>originalCount;check(bool(directory)&&directoryTag=="EXTENSIONS","Read generated extension directory");
    write(bad,payload.substr(0,extension)+"EXTENSIONS "+std::to_string(originalCount+1)+"\n"+payload.substr(directoryEnd+1)+"AXIS_RATE_LIMITS 1 "+std::to_string(axisBlock.size())+"\n"+axisBlock);
    auto assessedLoaded=loaded;check(loadDesign(bad.string(),assessedLoaded,error)&&assessedLoaded.accepted(),"Parsed assessed rate receives actual passing half-step verification");near(assessedLoaded.request.limits.maxLateralRateGps,1000,0,"Configured axis limit persists exactly");check(std::isnan(assessedLoaded.request.limits.maxLongitudinalRateGps),"Unassessed axis stays unassessed");check(serializeReference(assessedLoaded.request.targets.reference)==serializeReference(t.reference),"Valid appended axis extension preserves typed evidence");
    auto assessedPath=folder/"typed-assessed.coaster";check(saveDesign(assessedLoaded,assessedPath.string(),error),"Verified assessed profile can be saved");Design assessedReplay;check(loadDesign(assessedPath.string(),assessedReplay,error)&&reportJson(assessedReplay)==reportJson(assessedLoaded),"Assessed profile save and full reverified replay agree");
    ComparisonHistory h;check(h.commit(d)&&!h.previous.available,"First accepted commit no previous");auto unchecked=d;unchecked.convergence={};check(!h.commit(unchecked)&&h.current.seed==d.request.seed&&!h.previous.available,"Unverified ride does not shift history");auto failed=d;failed.report.fail("TEST","test");check(!h.commit(failed)&&h.current.seed==d.request.seed&&!h.previous.available,"Failed commit does not shift history");auto second=d;second.request.seed=99;check(h.commit(second)&&h.current.seed==99&&h.previous.seed==d.request.seed,"Only accepted commit shifts comparison");auto lines=comparisonLines(second,&h.previous);check(std::any_of(lines.begin(),lines.end(),[](const auto& s){return s.find("uncertainty not quantified")!=std::string::npos;}),"Unquantified uncertainty visible");check(std::any_of(lines.begin(),lines.end(),[](const auto& s){return s.find("UNASSESSED")!=std::string::npos;}),"Unassessed axes visible");
    const auto legacyPath=std::filesystem::path(__FILE__).parent_path()/"fixtures/legacy-v021.coaster";auto retained=loaded;const auto legacyBytes=bytes(legacyPath);check(!loadDesign(legacyPath.string(),retained,error),"Older geometry schema is explicitly unsupported");check(error.find("unsupported schema")!=std::string::npos,"Old geometry is not silently reinterpreted");check(reportJson(retained)==reportJson(loaded)&&bytes(legacyPath)==legacyBytes,"Unsupported load preserves prior design and source bytes");
    std::cout<<"PASS "<<checks<<" reference/axis/comparison/extension checks (synthetic data only)\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
